---
abstract: 'RESTAS::Yars server'
author: []
build_requires:
  Clustericious: 0.04
  Test::More: 0
  Test::Pod::Coverage: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RESTAS-Yars
provides:
  RESTAS::Yars:
    file: lib/RESTAS/Yars.pm
    version: 0.02
  RESTAS::Yars::Routes:
    file: lib/RESTAS/Yars/Routes.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
