---
abstract: 'Yars Server'
author: []
build_requires:
  Clustericious: 0.79
  Clustericious::Config: 0.07
  Digest::file: 0
  File::Compare: 0
  File::Copy: 0
  File::Find: 0
  File::Find::Rule: 0
  Filesys::Df: 0
  Hash::MoreUtils: 0
  List::MoreUtils: 0
  List::Util: 0
  Mojolicious: 2.62
  Test::More: 0
  Test::Pod::Coverage: 0
  Try::Tiny: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Yars
provides:
  Yars:
    file: lib/Yars.pm
    version: 0.68
  Yars::Balancer:
    file: lib/Yars/Balancer.pm
  Yars::Routes:
    file: lib/Yars/Routes.pm
  Yars::Tools:
    file: lib/Yars/Tools.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.68
