---
abstract: 'Yars Server'
author: []
build_requires:
  Clustericious: 0.41
  Clustericious::Config: 0
  Clustericious::RouteBuilder: 0
  Test::More: 0
  Test::Pod::Coverage: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Yars
provides:
  Yars:
    file: lib/Yars.pm
    version: 0.21
  Yars::Routes:
    file: lib/Yars/Routes.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.21
